### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by haikukoten** [azizjalel/Compound-Watcher#2]
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    parse()
  File "/root/Compound-Watcher/files/modules.py", line 126, in parse
    bresult_borrow = "{:.8f} ".format(round(float(balance_borrow), 8)) + token_symbol(token_address)
TypeError: must be str, not NoneType

**Comment by saszer** [comment]
did you get around this?

**Comment by tdudz** [comment]
same issue still

**Comment by tdudz** [comment]
to fix it just merge the pull request that adds cDAI support for address 0x5d3a536e4d6dbd6114cc1ead35777bab948e3643
