### ISSUE TITLE
Websocket error 

### ISSUE THREAD

**Issue by stefanandy** [azizjalel/Compound-Watcher#3]
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from modules import *
  File "C:\Users\Lejer\PycharmProjects\Compound-Watcher\files\modules.py", line 18, in <module>
    if w3.isConnected() == True:
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\main.py", line 260, in isConnected
    return self.provider.isConnected()
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\providers\base.py", line 103, in isConnected
    response = self.make_request(RPCEndpoint('web3_clientVersion'), [])
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\providers\websocket.py", line 139, in make_request
    return future.result()
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\providers\websocket.py", line 119, in coro_make_request
    async with self.conn as conn:
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\providers\websocket.py", line 68, in __aenter__
    uri=self.endpoint_uri, loop=self.loop, **self.websocket_kwargs
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "C:\Users\Lejer\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401

**Comment by TennisBowling** [comment]
I have the same problem

**Comment by TennisBowling** [comment]
@azizjalel please advise
